### ISSUE TITLE
config.js中siteUrl设置报错

### ISSUE THREAD

**Issue by KiLien** [mayneyao/gine-blog#10]
修改aboutPostSlug及blog对应的url；

<img width="657" alt="微信截图_20190715111738" src="https://user-images.githubusercontent.com/13886339/61194135-33087700-a6f2-11e9-9338-f9e7506e9216.png">

部署至Netlify，对应站点无效，这是没法适用Netlify的站点？
<img width="419" alt="微信截图_20190715111420" src="https://user-images.githubusercontent.com/13886339/61194052-ba091f80-a6f1-11e9-8fde-07e033d6e324.png">

**Comment by KiLien** [comment]
没事了

**Comment by mayneyao** [comment]
迟到的回复(
感谢反馈&使用这个项目搭建博客（没想到真的有人用...)，报错原因是文章表格中存在空白行，现已修复（显然你已经发现了这个问题）

代码中存在很多写死的配置，一些配置项没有起到对应的效果。对使用者造成一定的困扰，深感歉意。

头像以及底部 Copyright 名称的配置现已正常。参见: https://github.com/mayneyao/gine-blog/releases/tag/v0.4.5

如果打算长期使用这个项目搭建博客，欢迎 PR 以及建设性的讨论 :D
