### ISSUE TITLE
yarn build 报错，请问怎么办？

### ISSUE THREAD

**Issue by heloook** [mayneyao/gine-blog#16]
$ yarn build
yarn run v1.17.3
$ gatsby build
success open and validate gatsby-configs - 0.074 s
success load plugins - 0.341 s
success onPreInit - 0.077 s
success delete html and css files from previous builds - 0.072 s
success initialize cache - 0.066 s
success copy gatsby files - 0.150 s
success onPreBootstrap - 0.060 s
从本地获取文章缓存: Copy of gine-blog 使用文档
success source and transform nodes - 7.948 s
success Add explicit types - 0.058 s
success Add inferred types - 0.195 s
success Processing types - 0.107 s
success building schema - 0.465 s
格言保存成功
success createPages - 0.144 s
success createPagesStatefully - 0.108 s
success onPreExtractQueries - 0.062 s
success update schema - 0.084 s
warn The GraphQL query in the non-page component
"E:/gine-blog-master/src/components/bangumi/index.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — http://graphql.org/learn/queries/#fragments
success extract queries from components - 0.288 s
success write out requires - 0.064 s
success write out redirect data - 0.056 s
success onPostBootstrap - 0.063 s
⠀
info bootstrap finished - 14.346 s
⠀
success run static queries - 0.069 s
success Building production JavaScript and CSS bundles - 28.135 s
success Rewriting compilation hashes - 0.231 s
success run page queries - 0.096 s — 6/6 173.69 queries/second

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  TypeError: Object(...) is not a function

  - render-page.js:55970 createPageContext
    E:/gine-blog-master/public/render-page.js:55970:107

  - render-page.js:55972 getPageContext
    E:/gine-blog-master/public/render-page.js:55972:29

  - render-page.js:708 Object.replaceRenderer
    E:/gine-blog-master/public/render-page.js:708:22

  - render-page.js:120
    E:/gine-blog-master/public/render-page.js:120:107

  - Array.map

  - render-page.js:120 ./.cache/api-runner-ssr.js.module.exports
    E:/gine-blog-master/public/render-page.js:120:21

  - render-page.js:562 Module../.cache/static-entry.js.__webpack_exports__.defau    lt
    E:/gine-blog-master/public/render-page.js:562:1

  - render-html.js:35
    [gine-blog-master]/[gatsby]/dist/utils/worker/render-html.js:35:36

  - debuggability.js:313 Promise._execute
    [gine-blog-master]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:488 Promise._resolveFromExecutor
    [gine-blog-master]/[bluebird]/js/release/promise.js:488:18

  - promise.js:79 new Promise
    [gine-blog-master]/[bluebird]/js/release/promise.js:79:10

  - render-html.js:31
    [gine-blog-master]/[gatsby]/dist/utils/worker/render-html.js:31:37

  - util.js:16 tryCatcher
    [gine-blog-master]/[bluebird]/js/release/util.js:16:23

  - map.js:61 MappingPromiseArray._promiseFulfilled
    [gine-blog-master]/[bluebird]/js/release/map.js:61:38

  - promise_array.js:114 MappingPromiseArray.PromiseArray._iterate
    [gine-blog-master]/[bluebird]/js/release/promise_array.js:114:31

  - promise_array.js:78 MappingPromiseArray.init
    [gine-blog-master]/[bluebird]/js/release/promise_array.js:78:10

⠏ Building static HTML for pages
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by heloook** [comment]
这个问题没有了。我重新走了一遍流程，跟先前不一样的是：（1）这次先安装 puppeteer，再yarn；（2）我之前是先把yarn.lock删了，然后yarn，重新生成lock文件。这次没有删。 
搞不懂这些是什么东西，瞎试

**Comment by heloook** [comment]
我弄好啦，[我的博客](https://www.heloook.com)，欢迎来访。

**Comment by mayneyao** [comment]
> 我弄好啦，[我的博客](https://www.heloook.com)，欢迎来访。

恭喜🎉🎉🎉。希望博客能坚持写下去，共勉😌

我真是太感动了，终于有人用这个轮子了（你应该是第一个正式用户👏）。使用过程中有什么疑问/bug/建议，可以私信我或者提 issues 哦。

**Comment by heloook** [comment]
哇塞，第一个用户，这感觉太棒啦！
