### ISSUE TITLE
求助，以及一些使用反馈

### ISSUE THREAD

**Issue by heloook** [mayneyao/gine-blog#19]
最重要的求助：
我的博客在不翻墙的情况下，访问速度极慢，请问我该怎么做，才能加快在国内访问博客的速度？我在网上没找到合适的方法

使用反馈：总体是很满意的，说一些小问题。
（1）格言 个性化 无效
我已经改成自己的notion链接了，
`// 格言
    aphorisms: {
        open: true, // 默认关闭 需要api
        sourceType: 'notion',
        url: 'https://www.notion.so/heloook/f38854123bac4aebb2955195c9317fcb?v=d2f3e81650284812a59defdfa282e661', // notion 表格地址
        // 返回格式参见上面链接的内容
    },`
但是还是显示以前的：
![image](https://user-images.githubusercontent.com/27837566/63951913-2cbb3800-cab1-11e9-91e2-c7141636d21b.png)
（2）博客侧边栏现在是自动隐藏，能不能加上 固定显示侧边栏的配置选项，我比较习惯固定住侧边栏的样子。大神有时间的话可以考虑把这个问题优化一下子。达到像hexo那种样子就比较完善了。
（3）有个问题对我没什么影响，但我还是指出来吧。这个问题是notion本身带来的问题。就是，如果我在博客文章中留下了某个notion笔记的链接，那么就可以点击到“文章”页，如果我有一些未发布的博客，此时那些未发布的博客就会暴露出来了。因为notion的子页无法单独设置文章的共享性，“文章”页共享了，那么未发布的草稿肯定也被看到了。

最关键的是最上面的求助，我现在完全不知道该怎么解决。。。

**Comment by mayneyao** [comment]
1. 国内访问加速
Netlify 的 CDN 对国内用户非常不友好，访问很慢。你可以将域名 DNS 设置为 Cloudflare ，cf 会提供 cdn 的功能，访问速度会快一些。具体操作以 cloudflare netlify 为关键词搜索，可以查到很多文章。

2. 格言的设置无效
看了下代码，是配置没用上。想要快速修改的话，修改 gine-blog/src/notion/aphorisms.js 第6行。

3. 关于样式的配置
后续会改写成主题切换的模式（鸽很久），底层已经跟 notion 绑死了，不打算再去适配其它数据源，配置也会尽量迁移到 notion 中。 Gatsby 不像是 hexo 那种专门写博客的，hexo 有格式统一的数据源，所以有丰富的主题可供选择，切换。Gatsby没有固定的数据格式，博客主题生态较差。

4. 这个问题确实没法处理，尽量避免在已经发布的文章中，引用未发布的文章。一般来说都是后者引用前者，所以这个问题出现的比较少。如果不希望未发布的文章（半成品）被人看到。可以建立一个私密的表格来管理这些文章，在文章写完后，移动到现在的表格中去。

**Comment by heloook** [comment]
收到！
