### ISSUE TITLE
打开http://localhost:8000/提示404

### ISSUE THREAD

**Issue by wilfzhao** [mayneyao/gine-blog#20]
执行完安装-运行-部署里的yarn build之后，打开ttp://localhost:8000/，出现如下图提示
![image](https://user-images.githubusercontent.com/48481525/64060554-00aecc80-cc01-11e9-987d-8ca851860f94.png)

**Comment by mayneyao** [comment]
看起来是因为文章内容没有正常获取到。没有 log 不好判断，还是贴下log比较好。

**Comment by wilfzhao** [comment]
已解决，是我Gatsby的路径有问题导致的
