### ISSUE TITLE
书单链接在config.js中修改后，无法生效

### ISSUE THREAD

**Issue by YuHoYe** [mayneyao/gine-blog#21]
书单链接在config.js里修改后无法生效
应该是下面的文件中的第196行所导致
src/notion/syncBlog.js
`let url = 'https://www.notion.so/98717bf8ad57434eafd9a65277403c33?v=fa4f00bb9b5b492fb23157f8d5df471f'`
可以修改成
`let url = config.book.url`
PS：怎么才能在大陆稳定访问？我经常连netlify都打不开

**Comment by mayneyao** [comment]
谢谢反馈。加速可以参考这个 issue下的讨论 
https://github.com/mayneyao/gine-blog/issues/19

**Comment by YuHoYe** [comment]
感谢
我已将域名的DNS设置为cf提供的服务器
并在cf里设置了将my-blog.netlify.com指向my.com
然后把Netlify里面的DNS设置删除了
请问这样的操作正确么，因为等了一段时间my.com并不能访问

**Comment by mayneyao** [comment]
Netlify 中会出现 Check DNS configuration 警告，但是并不影响，不用操作。 dns 迁移到 cf 需要一段时间后才能生效。

**Comment by YuHoYe** [comment]
已更改
有个疑问，这个104.198.14.52是netlify的什么ip，我的理解这不应该是yournetlifydomain.netlify.com的ip么

**Comment by YuHoYe** [comment]
> 已更改
> 有个疑问，这个104.198.14.52是netlify的什么ip，我的理解这不应该是yournetlifydomain.netlify.com的ip么

满地打滚求解答

**Comment by mayneyao** [comment]
netlify 里面有说明的，这个 ip 是 netlify 负载均衡服务器的 ip

```
DNS configuration
There are two options for pointing a root domain to Netlify.

Recommended: point ANAME or ALIAS record to gine.netlify.com
Use a DNS provider that supports ANAME or ALIAS records, and alias gine.me to gine.netlify.com.

We recommend using NS1 or Netlify’s built-in DNS service for this.

gine.me ALIAS gine.netlify.com.
Alternative: point A record to 104.198.14.52
Create an A record for gine.me pointing to our load balancer’s IP address 104.198.14.52.

gine.me A 104.198.14.52
Warning! With your current configuration, you won’t benefit from the full advantages of a CDN if you use an A record.

We recommend setting www.gine.me as your primary custom domain, or switching to a DNS provider that supports ANAME or ALIAS records.

If you’ve already done this, allow up to 24 hours for the changes to propagate, or check our documentation for more information.
```

**Comment by YuHoYe** [comment]
原来是这样！感谢！
