### ISSUE TITLE
开启PWA后编译不通过

### ISSUE THREAD

**Issue by YuHoYe** [mayneyao/gine-blog#22]
### 错误信息

8:58:48 PM: yarn run v1.17.3
8:58:48 PM: $ gatsby build
8:58:51 PM: error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.
8:58:51 PM: 
**8:58:51 PM:   TypeError: Cannot read property 'runtimeCaching' of undefined**

### 导致错误的提交记录
https://github.com/mayneyao/gine-blog/commit/54ab729283cd6e70df37f0674c38ce1cd0a39c46
似乎是想配置SW，但是最终的master中没有相关的代码，导致出错
把SW相关的下列代码注释可编译通过。不过不知道这样PWA还有没有生效。
```
    // sw 重载
    let swConf = config.pwa.swConf

    // 对基于 nelify functions 动态页面，缓存其请求
    swConf.runtimeCaching.push({
        // Add runtime caching of various other page resources
        urlPattern: /^https?:.*\/.netlify\/functions\/notion/,
        handler: `staleWhileRevalidate`,
    })

    conf.plugins.push({
        resolve: `gatsby-plugin-offline`,
        options: swConf,
    })
```

**Comment by mayneyao** [comment]
谢谢反馈，修复见 https://github.com/mayneyao/gine-blog/commit/9784c6d496f615ffb4500e997d9166e974b39169

**Comment by YuHoYe** [comment]
谢谢修复
