### ISSUE TITLE
开启openGithubCache后build失败

### ISSUE THREAD

**Issue by wilfzhao** [mayneyao/gine-blog#24]
本地环境变量已配置
![image](https://user-images.githubusercontent.com/48481525/64477604-3be86700-d1d0-11e9-89df-ac357143ddae.png)

执行yarn build时提示
error We encountered an error while trying to load your site's gatsby-config.

  Error: 因为您开启了github仓库缓存notion文章，请配置环境变量 GitHubToken

  - gatsby-config.js:103 Object.<anonymous>
    E:/Blog/gine-blog/gatsby-config.js:103:11

  - v8-compile-cache.js:178 Module._compile
    [gine-blog]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:789 Object.Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32

  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12

  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3

  - loader.js:692 Module.require
    internal/modules/cjs/loader.js:692:17

  - v8-compile-cache.js:159 require
    [gine-blog]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - get-config-file.js:26 getConfigFile
    [gine-blog]/[gatsby]/dist/bootstrap/get-config-file.js:26:20

  - index.js:96 module.exports
    [gine-blog]/[gatsby]/dist/bootstrap/index.js:96:36

  - develop.js:362 module.exports
    [gine-blog]/[gatsby]/dist/commands/develop.js:362:13

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

⠋ open and validate gatsby-configs
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by mayneyao** [comment]
这个配置没啥实际意义了，关闭配置即可。开始用 github 缓存文章是为了加速 build 。现在默认是从本地缓存中获取内容，速度会快很多。

**Comment by wilfzhao** [comment]
好的，谢谢！
