### ISSUE TITLE
感谢大家的使用和反馈，近期打算重构项目并完善文档。

### ISSUE THREAD

**Issue by mayneyao** [mayneyao/gine-blog#26]
近日收到的反馈增多，大多数是在部署和配置方面出现问题。接下来重构项目会让部署和配置变得简单。

下面是一些改进的方向
+ 项目拆分为 gine-blog 和 gatsby-source-notion-database
+ gatsby theme 是 Gatsby 社区推出的新特性，gine-blog 会变成 theme 插件，你可以以安装 npm 包的形式安装 gine-blog。并且可以重载主题，满足自定义的需求。同时可以享受此博客的底层数据功能和一些新特性。
+ gatsby-source-notion-database 是 Gatsby 插件，会把 notion database 中的数据转化为 Gatsby 中可用的数据源。
+ 与 notion 深度耦合。开始造轮子时，希望轮子能够通用一些，适配不同的数据源。个人使用一段时间后，逐渐认可 notion all-in-one 的理念。接下来不会再考虑其它数据源的适配。基础配置项会从 notion 表格中获取。
+ 完善中文文档，添加英文文档（尽量）

大家有什么需求和建议可以在此 issue 中回复

**Comment by YuHoYe** [comment]
希望能有类似书单的影单功能。我试着实现了，但是有不少bug。

**Comment by wilfzhao** [comment]
非常感谢大佬！
现在的配置文档，对于非IT人员来讲的话，看起来有点困难，也就是说有点地方写的还不够详细。

**Comment by mayneyao** [comment]
@YuHoYe @wilfzhao  我建了个微信交流群，大家感兴趣的话可以加一下。
![](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fee3af448-1bc5-4b7a-ac21-f1c2d3070ded%2Fmmqrcode1568030948692.png?table=block&id=ee35b35f-e706-4e17-95fe-1ba1645f3e2f&width=400&cache=v2)

**Comment by dongsuo** [comment]
你好，二维码已过期，请问可以拉我入群吗，base64: V0hVX1hYRg==
