### ISSUE TITLE
配置moments的问题

### ISSUE THREAD

**Issue by wilfzhao** [mayneyao/gine-blog#27]
moments: {
        open: true,
        url: “”
    }

配置文件中的双引号，是不是要改成单引号。我试了如果是双引号不显示，单引号就没有问题

**Comment by YuHoYe** [comment]
双引号也行的吧，你这引号看起来是全角的，试试半角。

**Comment by wilfzhao** [comment]
感谢指正，应该是半角的

**Comment by wilfzhao** [comment]
配置完moments之后点开，页面最上方进度条一直在跑，但是moments的内容没有出来，类似书单等其他模块都是正常的 @mayneyao
