### ISSUE TITLE
Notion中的Toggle List未支持

### ISSUE THREAD

**Issue by miranquil** [mayneyao/gine-blog#30]
如果使用Toggle List，文章中仅仅会显示折叠时的小标题和三角，三角确实可点击但没有任何响应，源码中也没有折叠钓的内容。

**Comment by miranquil** [comment]
此外，在Safari浏览器下存在Notion表格列数过多时越过页面边框的问题（下方滑动条消失）。

**Comment by mayneyao** [comment]
... 被发现了。这2个问题，我都遇到了。
Toggle List 的内容是异步加载的，只有点击之后才会抓取数据，渲染。puppeteer 可以做但是有点麻烦，特别是 Toggle List 嵌套的时候，这样会增加单个文章的抓取时间。建议文章中不使用 Toggle List。（或许我该写个表格，说明一下支持的 block 类型）

表格的显示问题，是因为 CSS `overflow : scroll hidden` 这样的写法在 Safari 上不兼容（会报错），旧版的 Edge 也有这个问题。

可能 Notion 之后还会出其它的 block，如果也存在问题，一个个的修复 CSS 太麻烦。我开始思考用 puppeteer 抓 html 是不是稍微重了一些，准备直接用数据渲染成 html。这里有个现成的解决方案 https://github.com/dragonman225/nast-util-from-notionapi 但是 block 的支持也不是很全面，CSS 也需要自己重新写。个人还是喜欢 Notion 原生的样式，所以这个想法暂缓了。

感谢反馈。有什么好的想法或者思路，欢迎讨论😀

**Comment by miranquil** [comment]
OK，我自己研究一下先，辛苦啦！

**Comment by mayneyao** [comment]
表格的显示问题，我稍后修复一下。然后文档说明一下支持的 block。

最近在折腾 notion 自定义域名+ disqus 评论。如果想用 Notion 做博客，同时对 SEO 和自定义页面没什么特殊需求的话，可以采用这个方案。这里有个 Demo ：https://agodrich.com

**Comment by miranquil** [comment]
> 表格的显示问题，我稍后修复一下。然后文档说明一下支持的 block。
> 
> 最近在折腾 notion 自定义域名+ disqus 评论。如果想用 Notion 做博客，同时对 SEO 和自定义页面没什么特殊需求的话，可以采用这个方案。这里有个 Demo ：https://agodrich.com

感觉这个不错，有文档什么的吗？

**Comment by mayneyao** [comment]
目前还没有，我是准备这几天发的。是一个基于 Cloudflare Worker 的解决方案，应该可以满足做博客的基础需求。前身就是自定义域名，现在把 disqus 加上了，后面可能添加对其它第三方评论的支持，ga 什么的应该也都会有。
https://gine.me/posts/466ca19681634b09b123067f880ea396
https://gist.github.com/mayneyao/b9fefc9625b76f70488e5d8c2a99315d

**Comment by mayneyao** [comment]
> > 表格的显示问题，我稍后修复一下。然后文档说明一下支持的 block。
> > 最近在折腾 notion 自定义域名+ disqus 评论。如果想用 Notion 做博客，同时对 SEO 和自定义页面没什么特殊需求的话，可以采用这个方案。这里有个 Demo ：https://agodrich.com
> 
> 感觉这个不错，有文档什么的吗？

@yorushika  https://gist.github.com/mayneyao/b9fefc9625b76f70488e5d8c2a99315d
