### ISSUE TITLE
图片居中的问题

### ISSUE THREAD

**Issue by curiosity654** [mayneyao/gine-blog#35]
首先非常感谢这个项目，使用真的很方便
部署后在notion中设置居中的图片在网页里不居中，看着挺难受的，不知能否解决？

**Comment by mayneyao** [comment]
目前的实现方案，图片应该是 100% 宽度的，这样对移动端友好一点。

样式问题不会修复，你可以自己写样式覆盖重载。见谅😂
改这里就好了。https://github.com/mayneyao/gine-blog/blob/master/src/index.css#L11

**Comment by curiosity654** [comment]
好的，确实对移动端挺不错，谢谢啦😂
